const PORT = process.env.PORT || 3000;

const pool = mariadb.createPool({
     host: 'localhost',
     port: '3306',
     user:'root',
     password: 'password',
     connectionLimit: 50,
     database: 'sporksdb'
});